#!/bin/bash
echo "=== DIAGNÓSTICO DE CONFIGURACIÓN ==="
echo ""
echo "El problema es que:"
echo "1. Tu sitio usa HTML estático (index.html, articulo-agua.html, etc.)"
echo "2. Netlify CMS guarda artículos en formato Markdown (.md)"
echo "3. No hay un proceso de 'build' que convierta .md → .html"
echo ""
echo "Por eso los artículos que creas NO aparecen en el sitio."
echo ""
echo "=== SOLUCIONES POSIBLES ==="
echo ""
echo "OPCIÓN A (MÁS SIMPLE): Sistema híbrido JavaScript"
echo "  • Mantener tu sitio HTML actual"
echo "  • Agregar script que lea los .md y los muestre dinámicamente"
echo "  • Netlify CMS funcionará inmediatamente"
echo "  • Ventaja: No cambias nada de lo que ya tienes"
echo ""
echo "OPCIÓN B (MÁS PROFESIONAL): Migrar a generador estático"
echo "  • Usar Eleventy (11ty) o similar"
echo "  • Convertir tus HTMLs a templates"
echo "  • Sistema completo .md → .html"
echo "  • Ventaja: Escalable y profesional"
echo ""
echo "OPCIÓN C (MANUAL): Editor de archivos directo"
echo "  • Usar Forestry.io o Git-based CMS"
echo "  • Editar HTMLs directamente sin Markdown"
echo "  • Ventaja: Control total"
